version: '3.8'

services:
  web:
    build: ./flask_app
    ports:
      - "5000:5000"  # Expose port 5000 of the container to port 5000 on the host
    depends_on:
      - db
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0  # Ensure Flask listens on all network interfaces

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/postgresql/data  # Named volume for database persistence
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Bind mount for initialization script

volumes:
  db_data:  # Named volume definition
